title: Black Swan House
email: blackswan.emails@gmail.com
description: >-
  Book Publisher
baseurl: ""
url: "https:blackswan.house"
logo: /assets/img/logo.svg

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: Contact
    url: /contact/
  - title: Mail-In Form
    url: /mail-in-contact/