title: Black Swan House
email: blackswan.emails@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Book Publisher
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:blackswan.house" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/logo.png

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: Contact
    url: /contact/
  - title: Mail-In Form
    url: /mail-in-contact/